//test generated by chat gpt

#include "minic-stdlib.h"

struct Point {
    int x;
    int y;
};

int add(int a, int b) {
    return a + b;
}

int multiply(int a, int b) {
    int result;
    result = a * b;
    return result;
}

void printPoint(struct Point p) {
    print_s((char*)"Point coordinates: (");
    print_i(p.x);
    print_s((char*)", ");
    print_i(p.y);
    print_s((char*)")\n");
}

int computeArea(int length, int width) {
    // Calculate area of a rectangle
    int area;
    area = multiply(length, width);
    return area;
}

void main() {
    struct Point center;
    int length;
    int width;
    int area;
    int count;
    
    // Initialize variables
    center.x = 10;
    center.y = 5;
    length = 7;
    width = 4;
    count = 0;

    // Compute area of a rectangle
    area = computeArea(length, width);

    // Print the center point
    printPoint(center);

    // Print the area
    print_s((char*)"Area of rectangle: ");
    print_i(area);
    print_s((char*)"\n");

    // Simple while loop example
    while (count < 10) {
        print_s((char*)"Count: ");
        print_i(count);
        print_s((char*)"\n");
        count = add(count, 1);
    }

    // If-else statement
    if (area > 20) {
        print_s((char*)"Large rectangle.\n");
    } else {
        print_s((char*)"Small rectangle.\n");
    }
}
