//test generated by chat gpt

#include "minic-stdlib.h"

// Function to calculate the area of a circle using integers
int calculateArea(int radius) {
  int area;
  // Assuming pi is approximated by 3 (as we are using integers)
  area = 3 * radius * radius;
  return area;
}

void main() {
  int radius;
  int area;
  
  // Read radius from standard input
  print_s((char*)"Enter the radius of the circle: ");
  radius = read_i();

  // Calculate the area
  area = calculateArea(radius);

  // Print the result
  print_s((char*)"The approximate area of the circle is: ");
  print_i(area);
  print_s((char*)" (Note: This calculation uses an integer approximation of pi.)\n");
}
