// this code is generated by chat gpt as test code given the grammar

#include "minic-stdlib.h"

struct Node
{
    int data;
    struct Node *next;
};

void printList(struct Node *n)
{
    while (n != NULL)
    {
        print_i((*n).data);
        print_s((char *)" ");
        n = (*n).next;
    }
    print_s((char *)"\n");
}

void swap(struct Node *a, struct Node *b)
{
    int temp;
    temp = (*a).data;
    (*a).data = (*b).data;
    (*b).data = temp;
}

void bubbleSort(struct Node *start)
{
    int swapped;
    struct Node *ptr1;
    struct Node *lptr;

    lptr = NULL;

    if (start == NULL)
        return;

    swapped = 1;
    while (swapped)
    {
        swapped = 0;
        ptr1 = start;

        while ((*ptr1).next != lptr)
        {
            if ((*ptr1).data > (*((*ptr1).next)).data)
            {
                swap(ptr1, (*ptr1).next);
                swapped = 1;
            }
            ptr1 = (*ptr1).next;
        }
        lptr = ptr1;
    }
}

void main()
{
    struct Node *head;
    struct Node *second;
    struct Node *third;
    struct Node *fourth;

    head = (struct Node *)malloc(sizeof(struct Node));
    second = (struct Node *)malloc(sizeof(struct Node));
    third = (struct Node *)malloc(sizeof(struct Node));
    fourth = (struct Node *)malloc(sizeof(struct Node));

    (*head).data = 3;
    (*head).next = second;
    (*second).data = 1;
    (*second).next = third;
    (*third).data = 4;
    (*third).next = fourth;
    (*fourth).data = 2;
    (*fourth).next = NULL;

    print_s((char *)"Linked list before sorting:\n");
    printList(head);

    bubbleSort(head);

    print_s((char *)"Linked list after sorting:\n");
    printList(head);
}
